### ISSUE TITLE
Rename functions

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#105]
Presently most function names have `TDy` as a prefix. Here is a proposal to rename functions:

- Only functions that can be called by demos should have `TDy` as a prefix. All internal function
  should not have `TDy` prefix.

**Comment by jedbrown** [comment]
What's the intent of this? At most, I would only do that with `static` functions. We can use internal linkage, `__attribute__((visibility("hidden")))`, for internal functions. But anything with external linkage _must_ be namespaced. That would include anything with `T`, `D`, or `B` in the output of `nm -D $PETSC_ARCH/lib/libtdycore.so`. There are a number of issues currently, like `CheckSymmetric`, `ComputeTheta`, ...

**Comment by bishtgautam** [comment]
@jedbrown My reasoning was that to add `TDy` as a prefix to all functions was not providing any value.

- I don't understand internal linkage. A quick grep for `visibility("hidden")` in PETSc showed that it is used https://gitlab.com/petsc/petsc/-/blob/master/include/petscsys.h#L80. But I don't know how that is used. Is this spelled out in PETSc dev manual?

- The PETSc dev manual (2.2.3 bullet 15) says to use `PETSC_INTERN` or `PETSC_EXTERN` to control the visibility. e.g. https://gitlab.com/petsc/petsc/-/blob/master/include/petsc/private/dmdaimpl.h#L91. So, we can use the same strategy here.

**Comment by jedbrown** [comment]
Internal ("hidden") linkage means that the symbol is only available within the shared library. This makes the shared library a little smaller and calls can be slightly faster (no GOT/PLT indirection), but most importantly, they are not available to resolve references in user code. So if `CheckSymmetric` is internal, an application or other library is free to define and use their own function of the same name, without worry that it will conflict. If it's external, they could get linker errors or resolve unpredictably depending on the order in which libraries are passed to the linker.  It's bad library practice to expose _any_ unnamespaced symbols.

We should use internal (or static) linkage for anything we don't want in the public API, but I'd keep the namespace on anything that isn't `static`. It's so few letters it hardly hurts.

**Comment by bishtgautam** [comment]
@jedbrown Thanks for the explanation. 

I see that `PETSC_INTERN` --> `PETSC_VISIBILITY_INTERNAL` --> `__attribute__((visibility ("hidden")))`

**Comment by jedbrown** [comment]
Exactly, versus `PETSC_EXTERN`, which has default visibility (and thus is accessible to users). `nm -D` uses lowercase for internal symbols (and the names can be stripped), if you're interested in seeing the effect.

**Comment by jeff-cohere** [comment]
I agree with Jed--we don't want to pollute the namespace for applications linking against the library, and TDy is not a steep price to pay for distinguishing our functions from others.

**Comment by bishtgautam** [comment]
@jedbrown @jeff-cohere Okay, I'm convinced that including `TDy` is not a big cost. But, how do we differentiate between functions for the demos/applications and only the library? Should we add a suffix `_Private` as PETSc does?

**Comment by jeff-cohere** [comment]
I don't know how heavy-handed we have to be here. If I have to include a header in a `private/` directory to use a function, it's clear to me that I'm using an internal part of the library that isn't guaranteed to remain available or be supported. We can document that, too--functions declared in private headers are for library use and are unsupported.

I'm okay with adding suffixes to functions, too, but it might not be needed.

**Comment by jeff-cohere** [comment]
Can this be closed?
