### ISSUE TITLE
Impose a call sequence when setting up options

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#106]
After setup is called, don't allow demos to modify options. The following code should throw an error:

```
ierr = TDySetup(tdy); CHKERRQ(ierr);
ierr = TDySetDiscretizationMethod(tdy,MPFA_O); CHKERRQ(ierr);
```

**Comment by jeff-cohere** [comment]
This goes along with the discussion we were having a few weeks back about metadata (parameters fed to `TDySetup`) vs data (all the state information allocated and initialized by `TDySetup`).

**Comment by bishtgautam** [comment]
Agreed. #107 and this issue are related.
