### ISSUE TITLE
MPFA regression test run in parallel fails on linux

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#11]
The non-perturbed MPFA-O regression test fails on linux as reported by @ghammond86 in [this comment](https://github.com/TDycores-Project/TDycore/pull/10#issuecomment-492718410). Also, the parallel perturb MPFA-O test [failed on Travis-CI linux bot](https://travis-ci.org/TDycores-Project/TDycore/builds/531036397?utm_source=github_status&utm_medium=notification) and was thus disabled in 55bdb08df69e8df00805804a767211d4a35628bc.

**Comment by bishtgautam** [comment]
@ghammond86, When you get a chance could you test out `bishtgautam/fix-regression-key` branch. On this new branch, your linux bot should not report the extremely large pressure differences in the pressure values. I believe those large errors were because the domain decomposition for a parallel run on your linux bot and my mac were different, and I was saving an incorrect key in the regression file.

**Comment by ghammond86** [comment]
Still an issue:
mpfao-prob3-np3...
    cd /home/gehammo/software/TDycore/demo/mpfao
    mpiexec -np 3 /home/gehammo/software/TDycore/demo/mpfao/mpfao -malloc 0 -successful_exit_code 86 -problem 3 -tdy_regression_test -tdy_regression_test_num_cells_per_process 2 -tdy_regression_test_filename mpfao-prob3-np3
    # mpfao-prob3-np3 : run time : 0.10 seconds
    diff mpfao-prob3-np3.regression.gold mpfao-prob3-np3.regression
    FAIL: Liquid Pressure:11 : 0.436101069829 > 1e-12 [relative]
    FAIL: Liquid Pressure:22 : 0.751053231849 > 1e-12 [relative]
    FAIL: Liquid Pressure:Min : 4.65500182282e-06 > 1e-12 [relative]
    FAIL: Liquid Pressure:Max : 4.21984649937e-07 > 1e-12 [relative]
    FAIL: Liquid Pressure:42 : 0.295242507763 > 1e-12 [relative]
    FAIL: Liquid Pressure:53 : 0.35855734322 > 1e-12 [relative]
    FAIL: Liquid Pressure:0 : 0.947333335333 > 1e-12 [relative]
    FAIL: Liquid Pressure:32 : 0.820618259125 > 1e-12 [relative]
    FAIL: Liquid Pressure:Mean : 1.59981863819e-07 > 1e-12 [relative]
mpfao-prob3-np3... failed.

Gold File:
-- PRESSURE: Liquid Pressure --
      Max:   2.0022500827547e+00
      Min:   6.2638689972890e-02
     Mean:   7.0154314539634e-01
        0:   1.0282005661316e+00
       11:   5.4337566413506e-01
       22:   2.0022500827547e+00
       32:   1.4320570466511e+00
       42:   1.0817774839186e+00
       53:   5.5741587952100e-01

Glenn's Linux box:
-- PRESSURE: Liquid Pressure --
      Max:   2.0022492378359e+00
      Min:   6.2638981556106e-02
     Mean:   7.0154325763052e-01
        0:   2.0022492378359e+00
       11:   7.8034237258359e-01
       22:   4.9845368713131e-01
       32:   2.5688488606015e-01
       42:   1.4011641811122e+00
       53:   7.5728143635071e-01

**Comment by bishtgautam** [comment]
On my linux the test is passing and I have PETSc installed with the following configurations:
```
#!/usr/bin/env python
if __name__ == '__main__':
  import sys
  import os
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure_options = [
    '--download-parmetis=yes',
    '--download-metis=yes',
    '--download-hdf5=yes',
    '--download-netcdf=yes',
    '--download-netcdf=yes',
    '--download-openmpi=yes',
    '--download-sowing=yes',
    '--download-zlib=yes',
    '--download-fblaslapack=yes',
    '--download-hypre=yes',
    '--with-cc=/usr/bin/gcc-8',
    '--with-cxx=/usr/bin/g++-8',
    '--with-fc=/usr/bin/gfortran-8',
    'PETSC_ARCH=linux-gnu8'
  ]
  configure.petsc_configure(configure_options)
```

How is PETSc installed on your machine?

**Comment by ghammond86** [comment]
#!/usr/bin/python
if __name__ == '__main__':
  import sys
  import os
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure_options = [
    '--CFLAGS=-g -O0',
    '--CXXFLAGS=-g -O0',
    '--FFLAGS=-g -O0 -Wno-unused-function',
    '--PETSC_ARCH=gnu-c-debug',
    '--download-fblaslapack=yes',
    '--download-hdf5=yes',
    '--download-hypre=yes',
    '--download-metis=yes',
    '--download-mumps=yes',
    '--download-parmetis=yes',
    '--download-scalapack=yes',
    '--with-c2html=0',
    '--with-cc=mpicc',
    '--with-clanguage=c',
    '--with-cxx=mpicxx',
    '--with-debugging=1',
    '--with-fc=mpif90',
    '--with-shared-libraries=0',
    '--with-valgrind=1',
  ]
  configure.petsc_configure(configure_options)

The mpiXXX is mpich.  But how can differences in compiler version or optimizations produce differences in parallel, but not serial.

**Comment by bishtgautam** [comment]
just out of curiosity, which compiler version are you using? i would like to reproduce the similar failure on my machine.

**Comment by ghammond86** [comment]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

Too bad I don't have my new Linux box running PETSc.  It is running Linux Mint 19.1 (built on Ubuntu 18.04).
