### ISSUE TITLE
Add support for HDF I/O

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#111]
- [x] @satkarra will send a C code snippet for to output field in HDF5.

**Comment by satkarra** [comment]
I found a Fortran snippet.  @leorosie look at the line in boldface to add variable name.

-----------------------  



  implicit none

  type(pantra_type) :: pantra
  character(len=MAXSTRINGLENGTH), intent(in) :: filename
  character(len=MAXSTRINGLENGTH) :: name
  PetscViewer :: viewer
  PetscErrorCode :: ierr

  name = filename
  name = trim(adjustl(name)) // '.h5'
  call PetscViewerHDF5Open(pantra%option%mycomm,name,FILE_MODE_WRITE, &
                           viewer,ierr);CHKERRQ(ierr)
  call PetscViewerHDF5PushGroup(viewer, "/",ierr);CHKERRQ(ierr)
  **call PetscObjectSetName(pantra%x_flow,"pressure",ierr);CHKERRQ(ierr)**
  call VecView(pantra%x_flow,viewer,ierr);CHKERRQ(ierr)
  call PetscViewerDestroy(viewer,ierr);CHKERRQ(ierr)

**Comment by bishtgautam** [comment]
@leorosie Here are PFLOTRAN's xmf subroutines:

- [OutputXMFHeader](https://bitbucket.org/pflotran/pflotran/src/53166e5edf80919d91c2db41221771613774f291/src/pflotran/output_common.F90#lines-697)
- [OutputXMFFooter](https://bitbucket.org/pflotran/pflotran/src/53166e5edf80919d91c2db41221771613774f291/src/pflotran/output_common.F90#lines-809)
- [OutputXMFAttribute](https://bitbucket.org/pflotran/pflotran/src/53166e5edf80919d91c2db41221771613774f291/src/pflotran/output_common.F90#lines-836)

cc: @ghammond86
