### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#112]

**Comment by jedbrown** [comment]
Is it open for us to choose which license? 2-clause BSD (which PETSc uses) or MIT (roughly equivalent) are the simplest and most permissive. E3SM uses 3-clause BSD and PFLOTRAN is LGPL (so static linking of PFLOTRAN into E3SM would be prohibited).

**Comment by bishtgautam** [comment]
> Is it open for us to choose which license?

I haven't checked with PNNL to see if they prohibit a certain type of license. If there are no restrictions, we are free to choose the license.

**Comment by jeff-cohere** [comment]
Do you have to fill out paperwork with PNNL for them to approve open source software releases? In my experiences with LBNL and LLNL, that's when the license discussion usually happens.

**Comment by jedbrown** [comment]
What needs to be done here? Can we just choose or does it need to be approved (by whom)?

**Comment by jeff-cohere** [comment]
I would be surprised if anyone objects to a BSD license. That seems to be the license type of choice for the DOE these days.

**Comment by jedbrown** [comment]
Right, we do 2-clause BSD for PETSc. In new projects, I've been following Rust's strategy of dual-licensing MIT and Apache-2.0, which clarifies patent protections without restricting who can use it. I think either of these are fine choices, but (if allowed) we should decide soon.

**Comment by jeff-cohere** [comment]
@bishtgautam , do you want to start a conversation with PNNL's intellectual property folks and see whether they prefer BSD like the other labs? I also think the BSD/MIT/Apache 2 licenses are fine. Does anyone else have a stake in how TDycore is licensed?

**Comment by bishtgautam** [comment]
Let me check with PNNL IP folks and get back.
