### ISSUE TITLE
Upload documentation to tdycore.org

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#129]

**Comment by jeff-cohere** [comment]
Man, these tools are pretty horrible. Maybe my standards are too high.

Some guidance on publishing Sphinx stuff to GitHub Pages:
https://daler.github.io/sphinxdoc-test/includeme.html

**Comment by jedbrown** [comment]
Did you try this action? https://github.com/ammaraskar/sphinx-action

**Comment by jeff-cohere** [comment]
Thanks for that! I was looking for that link.
