### ISSUE TITLE
Introduce a unit testing mechanism/approach

### ISSUE THREAD

**Issue by jeff-cohere** [TDycores-Project/TDycore#138]
A discussion in #135 got us thinking about unit tests and how they can help isolate problems in a way that supplements more involved regression tests.

We discussed two options: 

1. A testing strategy used by PETSc that uses comment markup in a program to organize tests and reference data.
2. A standard testing framework (with the caveat that it needs to be parallel-capable).

Issue #135 provides us with an ideal candidate for a unit test: one creates a single "thing" (a mesh), performs some setup operations on it (including domain decomposition), and then checks its properties (for example, the control volumes surrounding nodes). The problem identified in that issue would cause this unit test to fail, and a successful fix would allow it to pass.

**Comment by bishtgautam** [comment]
@jeff-cohere What was the unit testing framework you mentioned on the call?

**Comment by jeff-cohere** [comment]
Here's some example code for a test that uses the [cmocka](https://cmocka.org) framework. It's very minimal compared to other fancypants testing frameworks, but it's expressive enough to make writing test code a bit easier.

```
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <string.h>
#include <cmocka.h>
#include <tdycore.h>

// This is a set of unit tests for functions in tdycore.c

static void testTDyCreate(void** state)
{
  TDy tdy;
  TDyCreate(&tdy);

  // Do some things!

  assert_true(expr_that_is_true);
  assert_false(expr_that_is_false);

  TDyDestroy(&tdy);
}

int main(int argc, char* argv[])
{
  TDyInit(argc, argv);
  const struct CMUnitTest tests[] =
  {
    cmocka_unit_test(TestTDyCreate),
  };
  int err = cmocka_run_group_tests(tests, NULL, NULL);
  TDyFinalize();
  return err;
}
```

Such a test could live in `src/tests/test_tdycore.c`, for example. Since we've organized all of the required initialization and finalization into the `TDyInit` and `TDyFinalize` functions, there's not much setup or breakdown needed to support parallel test cases. And it's very easy to create test "suites"--sets of functions related to areas of the code.

@jedbrown , @ghammond86 , @knepley , @bishtgautam : let me know if you want a more elaborate example, or if you have concerns about using something like this.

**Comment by jedbrown** [comment]
How would it work to `mpiexec -n 2 ./test_tdycore`? What if an assertion passes on some ranks but not others? Does it have a mode to at least move on to the next test (perhaps under a new process)?

**Comment by jeff-cohere** [comment]
Assertions cause a single test (function) to fail, but other tests still run. The library makes a pretty good effort to catch signals and try to isolate the tests without creating new processes. I've had a good experience with it in general.

For MPI: it's not magic, and it's not an HPC-aware library. But we should be able to call MPI inside of any given test--they run in the same order on each process. I think if we can agree on a strategy for handling tests that fail on a rank (which do signal failures, in the sense that they result in error codes being returned by the relevant processes), we can probably put together some helpers to make things easier to handle/understand. In this sense, it's no worse than any other standard testing framework. Of course, it's not going to be able to compete with a purpose-built HPC testing system in this regard. But again, I've had pretty good experiences using this in an HPC context personally.

**Comment by jedbrown** [comment]
So we'd create `collective_assert_eq(comm, left, right)` macros and be okay so long as we always clean up collectively (regardless of pass/fail). I'd be willing to try it.

The PETSc system is practical, but tries to fill multiple roles and has its share of shortcomings. If cmocka works well here, I could see it being adopted some places in PETSc (though that isn't a requirement for it to be useful for tdycore).
