### ISSUE TITLE
Does KDotADotB correctly represents the function?

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#25]
Should [`KDotADotB()`](https://github.com/TDycores-Project/TDycore/blob/master/src/tdywy.c#L136) be renamed as `KTimesADotB()`?

**Comment by nocollier** [comment]
If you feel more comfortable with it that way I am not opposed. The reason
is that the 'times' symbol means cross product when working with tensors
and that isn't what it is. It is the 2nd rank tensor K dot the 1st rank
tensor A dot the first rank tensor B.

Nate

**Comment by bishtgautam** [comment]
Ok, I see your point. How about `KMultADotB()` (similar to [`MatMult`](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatMult.html) of PETSc)?
