### ISSUE TITLE
Nonzero -successful_exit_code with Open MPI

### ISSUE THREAD

**Issue by jedbrown** [TDycores-Project/TDycore#34]
What is the rationale behind nonzero "success" exit codes? With Open MPI, it generates some crash output:
```
$ mpiexec --oversubscribe -n 3 /home/jed/src/tdycore/demo/steady/steady -malloc 0 -successful_exit_code 86 -tdy_regression_test -tdy_regression_test_num_cells_per_process 2 -tdy_regression_test_filename steady-wy-np3
1.562362e-02 7.702707e-04
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[22495,1],0]
  Exit code:    86
--------------------------------------------------------------------------
```

**Comment by bishtgautam** [comment]
I followed the logic that was used in regression testing in PFLOTRAN, when I implemented PFLOTRAN's regression testing infrastructure.

Glenn, Do you recall the rational behind nonzero success exit code in PFLOTRAN regression testing scripts?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghammond86** [comment]
I don’t recall the original logic back in 2012. But we key off it now to differentiate between user error and a crash.  Just set it to zero

Glenn

On Dec 16, 2019, at 3:31 PM, Gautam Bisht <notifications@github.com> wrote:

﻿I followed the logic that was used in regression testing in PFLOTRAN, when I implemented PFLOTRAN's regression testing infrastructure.

Glenn, Do you recall the rational behind nonzero success exit code in PFLOTRAN regression testing scripts?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
