### ISSUE TITLE
TDycore/demo/steady/steady.c

### ISSUE THREAD

**Issue by rezgarshakeri** [TDycores-Project/TDycore#41]
I've been studying `TDycore` repository and I understand that in line 325 of `steady.c` the mapping for 2D example is not what is represented in 2012Wheeler's paper.
Is there any reason for this discrepancy?
It seems in your code the z component of 3D is removed and used for 2D case.

Thanks,
Rezgar

**Comment by bishtgautam** [comment]
@rezgarshakeri, The 2D problem does not include a z-coordinate, thus the `cos(3*pi*z)` term is excluded when smoothly deforming the 2D mesh.

**Comment by rezgarshakeri** [comment]
I understand that.
What we have in Wheeler's paper (2012) for 2D example is:
x = x^ + 0.06 sin(2 pi x^) sin(2 pi y^)
y = y^ - 0.05 sin(2 pi x^) sin(2 pi y^).
But in `steady.c` as mentioned the z component of 3D case is excluded and we have:
x = x^ + 0.03 sin(3 pi x^) cos(3 pi y^)
y = y^ - 0.04 cos(3 pi x^) sin(3 pi y^).

That's the difference I meant.

**Comment by bishtgautam** [comment]
@rezgarshakeri I get your point now and you have correctly identified a bug.

**Comment by bishtgautam** [comment]
@rezgarshakeri Does https://github.com/TDycores-Project/TDycore/pull/42/commits/ecc57f6333881fd7d9861ecd995a361dbe997bbd fixes the issue?

**Comment by rezgarshakeri** [comment]
> @rezgarshakeri Does [ecc57f6](https://github.com/TDycores-Project/TDycore/commit/ecc57f6333881fd7d9861ecd995a361dbe997bbd) fixes the issue?

Yes, thank you
