### ISSUE TITLE
Ability for SNES-based time integrator to run to a certain time and pause

### ISSUE THREAD

**Issue by bishtgautam** [TDycores-Project/TDycore#68]

**Comment by jedbrown** [comment]
Do you want this to be like `TSSolve` to a target time or like an "event" that occurs at specified times/conditions?

**Comment by bishtgautam** [comment]
To be like `TSolve` to a target time. Below is the pseudo code for ELM-TDycore coupling.

```
call TDycoreSetDataFromELM(tdy, ...)
call TDycoreRunToDt(TDy, dtime) // dtime = 30 [min] usually
call TDycoreExtractDataForELM(tdy,...)
```

**Comment by nocollier** [comment]
I believe that TS can already do this and you have a few options:

https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/TS/TSSetExactFinalTime.html

You can opt to interpolate back to the final time or adapt the time step to
hit that time. Those options combined with:

https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/TS/TSSetMaxTime.html

I think that will do it?

Nate

**Comment by bishtgautam** [comment]
@nocollier, I agree with you that TS already has the required capability. I created this issue I was for the SNES-based time integrator option but did not accurately title this issue. I have now updated the title
